# Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: owo
    password: owo123
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml